#!/bin/bash

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
CLEAR='\033[00m'

MAIN_BRANCH=main

echo -e "${YELLOW}Fetching latest upstream${CLEAR}"
git fetch upstream

echo -e "${YELLOW}Resetting $MAIN_BRANCH${CLEAR}"
git checkout $MAIN_BRANCH > /dev/null
git reset --hard upstream/$MAIN_BRANCH

echo -e "${YELLOW}Pushing synced $MAIN_BRANCH${CLEAR}"
git push -f origin $MAIN_BRANCH

echo ""
echo -e "${GREEN}All synced :)${CLEAR}"
echo ""
