#!/usr/bin/env bash

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
CLEAR='\033[00m'

TRUNK_BRANCH=master

echo -e "${YELLOW}Fetching latest${CLEAR}"
git fetch

echo -e "${YELLOW}Resetting $TRUNK_BRANCH${CLEAR}"
git checkout $TRUNK_BRANCH > /dev/null
git reset --hard origin/$TRUNK_BRANCH

# echo -e "${YELLOW}Clearing stash${CLEAR}"
# git stash clear

echo -e "${YELLOW}Pruning removed remote branches${CLEAR}"
#git remote prune origin
git fetch --prune

echo -e "${YELLOW}Pruning merged branches${CLEAR}"
git branch --merged origin/$TRUNK_BRANCH \
  | egrep -v "^. (staging|$TRUNK_BRANCH)$" \
  | xargs -n 1 git branch -v -d

echo -e "${YELLOW}Pruning branching with deleted upstreams${CLEAR}"
git for-each-ref --format '%(refname:short) %(upstream:track)' \
  | awk '$2 == "[gone]" {print $1}' \
  | xargs -r git branch -D

echo -e "${YELLOW}Pruning unused commits${CLEAR}"
git prune

echo -e "${YELLOW}GC${CLEAR}"
git gc

echo ""
echo -e "${GREEN}All clean :)${CLEAR}"
echo ""
