#!/bin/sh

hostname="google.com"
interval_seconds=2
timeout_seconds=1

date_format="+%Y-%m-%d %H:%M:%S %Z"
red="\033[1;31m"
green="\033[1;32m"
clear="\033[0m"

echo "Hostname: $hostname"
echo "Interval: ${interval_seconds}s"
echo "Timeout: ${timeout_seconds}s"

trap "true" SIGALRM

while true; do
  line="->$hostname `date \"$date_format\"`"
  ping -t $timeout_seconds -qo "$hostname" &>/dev/null \
    && echo "${green}pass${clear} $line" \
    || echo "${red}FAIL${clear} $line"
  sleep $interval_seconds
done


